machines:
  raynor-pc: # Bryan
    data_root_prefix: "/home/bryan/mnt/cullen_data/"
  NikitaTower: # Nikita
    data_root_prefix: "Y:/"
  keondre-pc: # Keondre
    data_root_prefix: "A:/" 
  Keondres-MacBook-Air.local: # Keondre (Mac; key must match socket.gethostname())
    data_root_prefix: "/Volumes/data/"